### PR TITLE
Added EngineHub

### PR DESCRIPTION
**Pull request by me4502**

### CODE REVIEW

**Comment by SolarionFX** [comment]
Thanks @me4502

**Comment by me4502** [comment]
Hey I've noticed that new guilds that get added here get the server banner feature? Could I please get that added to EngineHub if possible?

We've already got the custom vanity URL feature.

Thanks :)

**Comment by me4502** [comment]
(Adding a ping @jamiebuilds sorry as I'm unsure if you'd get notified for an already closed PR)

**Comment by jamiebuilds** [comment]
This is a verified server so you already have some features turned on for your server. But I've gone ahead and enabled the [Server Banner](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image) feature for you.

**Pull request merged**
