### PR TITLE
adding TurtleCoin

### PR DESCRIPTION
**Pull request by RocksteadyTC**
Thanks for your consideration!

### CODE REVIEW

**Comment by UnknownHacker1125** [comment]
You need 1000 stars.

**Comment by nossr50** [comment]
> You need 1000 stars.

It's 1000 community members or 1000 stars

**Comment by DiscordAspekt** [comment]
As the others stated, right now we're featuring communities with over 1,000 stars. Feel free to resubmit when your community grows!

**Comment by RocksteadyTC** [comment]
@DiscordAspekt @Xoroxa @nossr50 
At the moment it says 1000 stars OR 1000 community members. We have hundreds of stars and over 14,000 community members. I think this deserves to be revisited.

**Pull request closed without merging**
