### PR TITLE
Add Panda3D

### PR DESCRIPTION
**Pull request by rdb**
Panda3D is an open-source game engine with a Discord server with, at time of writing, 1463 stars on GitHub:
https://github.com/panda3d/panda3d

Thanks for considering!

### CODE REVIEW

**Comment by SolarionFX** [comment]
I'd be happy to accept this PR, I just need you to resolve the conflicts!

**Comment by rdb** [comment]
@SolarionFX How's that?

**Comment by SolarionFX** [comment]
Hey there, I still see some conflicts. Can you please update this branch with master?

**Comment by rdb** [comment]
@SolarionFX rebased again, should be ready to merge.  Thanks!

**Comment by rdb** [comment]
@SolarionFX Merge conflict addressed again.  Could you merge this?  Thanks!

**Pull request merged**
