### PR TITLE
Add Quick.db

### PR DESCRIPTION
**Pull request by TrueXPixels**
[https://github.com/Plexi-Development/quick.db](https://github.com/Plexi-Development/quick.db)
[https://discordapp.com/invite/8nrEqvP](https://discordapp.com/invite/8nrEqvP)

### CODE REVIEW

**Comment by jfurrow** [comment]
@TrueXPixels I'd be happy to accept your PR, but I noticed your SVG has a base64 encoded PNG inside of it. Could you please submit either an SVG with vector shapes or a PNG with alpha transparency? The logo should be identifiable when we convert it to a single color.

**Comment by TrueXPixels** [comment]
Sorry about that, replaced the image with a png.

**Comment by jfurrow** [comment]
No problem @TrueXPixels. That looks better, but now it's in both the `logos` directory and the root directory — could you delete it from the root directory? Then this PR will be 👍

**Comment by TrueXPixels** [comment]
Ah, didn't see that. Thank you.

**Comment by jfurrow** [comment]
Perfect, thanks!

**Pull request merged**
