### PR TITLE
Add Vue.js ecosystem projects

### PR DESCRIPTION
**Pull request by robaxelsen**

### CODE REVIEW

**Comment by SolarionFX** [comment]
I'd be happy to accept this PR, but first, please make sure the logos are monochromatic and white. (check [the website](https://discordapp.com/open-source) for examples)

**Comment by robaxelsen** [comment]
Hi @SolarionFX, and thanks for the positive reply :tada: 

I've gone ahead and changed the logos to monochrome white. Please let me know if there are any issues.

**Comment by SolarionFX** [comment]
Looks good on my end, Thanks @robaxelsen!

**Comment by robaxelsen** [comment]
@SolarionFX two weeks later, and still not available on the "Discord - Open Source" page. Would you happen to know how often this is pulled/built?

Please let me know if there is anything I additional I need to do that I missed.

**Comment by jfurrow** [comment]
@robaxelsen we manually deploy the website as needed and I guess we just haven't had any other changes to deploy in the past two weeks. We're planning a deploy today so this will be included. In the future I'll be sure to deploy at a more regular cadence.

**Comment by jfurrow** [comment]
@robaxelsen They are live, visible after you click "View more":
screen shot 2018-11-14 at 10 11 12 am

**Comment by robaxelsen** [comment]
Great, thanks! See them now.

**Pull request merged**
