### PR TITLE
Added Rupaya to list of open source projects!

### PR DESCRIPTION
**Pull request by rupaya-project**

### CODE REVIEW

**Comment by jfurrow** [comment]
@rupaya-project Do you happen to have a single-color version of the logo? In its current form, this logo will render as a solid white circle.

**Comment by rupaya-project** [comment]
Will update with our new logo soon

**Comment by rupaya-project** [comment]
@jfurrow Logo has been updated

**Comment by jfurrow** [comment]
Beautiful, thanks @rupaya-project!

**Pull request merged**
