### PR TITLE
Add Akroma

### PR DESCRIPTION
**Pull request by OmarWazzan**
Added Akroma.

Website: https://akroma.io/
Github: https://github.com/akroma-project/akroma
Discord: https://discord.gg/UJxkpSx

Let me know if anything else is required, thanks!

### CODE REVIEW

**Comment by jfurrow** [comment]
Hey @OmarWazzan, thanks for the submission. Do you happen to have a version of the logo in a solid color? For the website, we adjust the color to be completely white, so with the PNG you submitted, the logo will appear as a solid white box.

Additionally, most of the logos we feature display the logomark without the type — would you be open to this?

I found an SVG on the Akroma website and modified it to show you what I'm trying to describe. It would look like this on our website:
akroma-example

Let me know what you think about these modifications.

**Comment by OmarWazzan** [comment]
That's fine. I have a few other logos, one of which is a white logo on a transparent background.

Thank you!

[discord.zip](https://github.com/discordapp/discord-open-source/files/1968863/discord.zip)

**Comment by OmarWazzan** [comment]
I'll upload the white transparent SVG now.

**Comment by jfurrow** [comment]
Beautiful, thanks @OmarWazzan!

**Pull request merged**
