### PR TITLE
Add JetBrains

### PR DESCRIPTION
**Pull request by MattIPv4**
JetBrains is a large developer of IDE software.
Many of the products and projects are open source.

Kotlin for example is open source and the repository has over 24k stars.
https://github.com/JetBrains/kotlin

The community version of the IntelliJ IDE is also on GitHub with over 6k stars.
https://github.com/JetBrains/intellij-community

Open source plugins written for the IntelliJ platform based IDEs are on GitHub and have over 1k stars.
https://github.com/JetBrains/intellij-plugins

The server itself is relatively small but we plan to slowly grow as the JetBrains community find it and join.

### CODE REVIEW

**Comment by jfurrow** [comment]
Thanks @MattIPv4!

Do you happen to have a version of the logo in a solid color? We display all logos in a white on the website, so the current logo would look like so:
jetbrains-solid-color

**Comment by jfurrow** [comment]
Using the solid-color logos at http://www.jetbrains.com/company/press/, I created a solid-color version that would look like this on our website:
jetbrains-modified

I'm not sure if it's against the brand guidelines, but if you'd like to use it, you can download the single-color version I created here:
jetbrains-solid-color-logo

**Comment by MattIPv4** [comment]
@jfurrow Thank you, hadn't realised absolutely everything would be white.

Whilst still most likely violating the brand guidelines as the box should stay black and untouched, I think your fix is the best that can be done. I have uploaded the updated icon as such.

**Comment by jfurrow** [comment]
Thanks @MattIPv4!

**Comment by MattIPv4** [comment]
Sorry to hijack the PR to continue...

Even with us being small, would we be considered for vanity url etc. based on the size of the repositories and company as whole?
Who would be best to contact regarding that?

**Comment by jfurrow** [comment]
@MattIPv4 No problem, I think your community would be well-suited for a vanity URL. Would you mind reaching out to opensource@discordapp.com fort this?

**Comment by MattIPv4** [comment]
@jfurrow Thanks, have just emailed in. :)

**Comment by JLuc** [comment]
Hello, it looks like there is an issue with jetbrain entry : the logo is OK in /logo folder, but there is no mention anymore of jetbrain in the communities.json It looks like it's been deleted there

**Comment by MattIPv4** [comment]
The community still exists in full swing but I believe it's not allowed to be listed here as I run it, not an employee, although we do have nearly 30 JetBrains employees there and they're happy for it to be the canonical server for JetBrains.

**Comment by JLuc** [comment]
Is there a reason why it should be employee run ? There is no such rule listed in https://github.com/discord/discord-open-source

**Comment by jamiebuilds** [comment]
Hey @MattIPv4 sorry it got removed for some reason. Would you mind making another PR?

I also turned on some features for you:

- [Vanity Invite URL](https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs)
- [Server Banner & Invite Splash](https://support.discord.com/hc/en-us/articles/360028716472-Server-Banner-Background-Invite-Splash-Image)

Do you want to update your invite code to something like `discord.gg/<yourprojectname>`?

**Comment by MattIPv4** [comment]
@jamiebuilds Awesome! I've set the vanity to `discord.gg/jetbrains`, seems the most appropriate. Would you like a new PR to re-add here?

**Comment by jamiebuilds** [comment]
Can you open a new one?

**Comment by MattIPv4** [comment]
#284 -- Tyvm 🙂

**Pull request merged**
