### PR TITLE
Add IntellectualSites

### PR DESCRIPTION
**Pull request by N0tMyFaultOG**

### CODE REVIEW

**Comment by SolarionFX** [comment]
I'd be happy to accept this PR, I just need you to resolve the conflicts!

**Comment by N0tMyFaultOG** [comment]
Here we go

**Comment by SolarionFX** [comment]
There are still conflicts in this PR, could you please update with the master branch and re-submit your changes?

**Comment by SolarionFX** [comment]
Thanks so much @N0tMyFaultOG!

**Pull request merged**
