### PR TITLE
Use new cdnjs brand (SVG)

### PR DESCRIPTION
**Pull request by MattIPv4**
cdnjs is in the process of rebranding, this PR updates the logo being used for the cdnjs server to match the new brand.

*Also now using SVG cause nicer™️*

### CODE REVIEW

**Comment by MattIPv4** [comment]
cc @AmNotADev

**Comment by DiscordAspekt** [comment]
Thanks for submitting your updated assets!

**Comment by MattIPv4** [comment]
Not a problem @DiscordAspekt - Could I email you to discuss upgrading the Discord server some more perhaps? (Or you can get in touch with me using matt@cdnjs.com if that’s better for you) :)

**Comment by DiscordAspekt** [comment]
Feel free to reach out to opensource@discordapp.com!

**Pull request merged**
