### PR TITLE
Add DenizenScript

### PR DESCRIPTION
**Pull request by mcmonkey4eva**

### CODE REVIEW

**Comment by SolarionFX** [comment]
Hey there, before I can review this request, can you resolve the conflicts and resubmit the logo as monochromatic white. You can find examples of this [here](https://discordapp.com/open-source).

**Comment by mcmonkey4eva** [comment]
@SolarionFX I'm not sure I should rebase against the new commit... I would recommend instead that you review the new commit that came in: https://github.com/discordapp/discord-open-source/commit/d375c5a667c7918c2b71a70e4ab3bd3d1d7faa0f and correct it prior to me rebasing this PR.
You'll notice it deletes the entry for "dvc" and replaces it with "flutter", which I believe was unintended.
That was from PR #150 by @kyleodev which deletes the additions of #147 by @SvetaGr 

---

Also, regarding the monochromatic white part:
Do you mean literally 1-bit color (white or transparent?) as opposed to what I submitted, which contains 2-bit color (white, gray, or transparent)?
I ask because a cursory glance through the logos folder shows several that use the white/gray/transparent palette (ie one form or another of grayscale). (Including, among others, the `flutter` PR that just came in and you're requesting I rebase against).
There are also at least 5 `.png` logos that include colors (buildcraft is brown, lindacoin and reasonml are red, ethergem and gentoo have purple).
If I'm interpreting correctly that you require white-or-transparent (1 bit) and absolute no other colors, there's a significant number of logos that need to be corrected accordingly.

**Comment by jfurrow** [comment]
@mcmonkey4eva The removal of the DVC community in https://github.com/discordapp/discord-open-source/commit/d375c5a667c7918c2b71a70e4ab3bd3d1d7faa0f was fixed just fixed upstream (https://github.com/discordapp/discord-open-source/commit/503ad86a9aa0044be182e3036caa2ff4e936bcbc), so please rebase against the latest in `master`.

With regard to your logo's colors, it's going to look bad on the website in its current form. A CSS filter is applied to the logos, which will make your logo solid white, essentially killing the current two-tone, 3D look. To keep your logo looking great, I suggest you swap the grey color for a pure-white with an alpha channel (check out https://github.com/discordapp/discord-open-source/blob/master/logos/gridsome.svg for example). That way your logo will retain its two-tone, 3D look. If you're not sure how to do this, I'd be happy to do it for you if you can provide a vector version of your logo.

The logos you're referencing aren't perfect, but render nicely on the website anyway because of the CSS filter, so they don't need to be corrected. We're asking that all new submissions adhere to the guidelines — just because they don't adhere to the guidelines doesn't mean yours shouldn't.

**Comment by mcmonkey4eva** [comment]
@jfurrow Thank you for the upstream fix and for clarifying!

I've converted the logo per your description (new 3 pixel colors are pure white, pure white 50% transparent, and pure transparent).
And as well have rebased the additions against the current upstream.

**Comment by SolarionFX** [comment]
Thanks @mcmonkey4eva

**Pull request merged**
