### PR TITLE
Add MinecraftOSS discord.

### PR DESCRIPTION
**Pull request by drtshock**
We're a discord of over 2500 users and 9 open source projects where we provide support and try to get other people to contribute to our projects <3

### CODE REVIEW

**Comment by DiscordAspekt** [comment]
Thanks for your interest, but at this moment in time, we are primarily focused on servers that are primarily focused on working on a particular project rather than a collection of smaller projects.

**Comment by drtshock** [comment]
The discord was created initially for Essentials which has 363 forks https://github.com/EssentialsX/Essentials/ and well over 1 million downloads https://www.spigotmc.org/resources/essentialsx.9089/ https://dev.bukkit.org/projects/essentialsx

You guys also accepted https://github.com/discordapp/discord-open-source/pull/115 not too long ago which is a similar community only with smaller projects...

**Comment by Andre601** [comment]
That is quite some incosistency...

**Comment by drtshock** [comment]
@DiscordAspekt Not sure how you have your notifications set so going to give a light ping :)

I understand it's your guys' prerogative who to accept and who not to, and that the support you guys give the open source community is greatly appreciated across the board. The MOSS discord has quite a few users that didn't make the jump from espernet IRC to discord until this guild was created. It's helped developers make the jump because it's so much easier to work together and provide support to our users, as well as find other contributors to help with both coding and supporting projects which of course helps keep people motivated to support FOSS in and often thankless environment.

Even if the answer is the same, that doesn't change how awesome it is that you guys let us do as much as you do on the platform without annoying monetization, so thanks <3

**Comment by DiscordAspekt** [comment]
I appreciate you checking in again! In the immediate term, we unfortunately won't be able to accept the server. We'll be reevaluating what types of servers we add to the Open Source program in the future.

**Comment by steve2132** [comment]
> I appreciate you checking in again! In the immediate term, we unfortunately won't be able to accept the server. We'll be reevaluating what types of servers we add to the Open Source program in the future.

Any news about this? Essentials have been a FOSS project for 7 years now and thus has significantly contributed to the open source Minecraft community. I wonder why companies like #115 got accepted for a bunch of small Minecraft assets, while not supporting open source due to their license which prevents users from "(re)distributing, publishing" the code. That means you can't even fork the repositories, for good reasons

**Comment by drtshock** [comment]
@DiscordAspekt any chance we can review this again? We've grown since I last submitted this. We added another open source project that has 13 million downloads https://dev.bukkit.org/projects/permissionsex and over 300 forks https://github.com/PEXPlugins/PermissionsEx. We're also up to over 5200 members.

These projects are 8+ years old. They're very open source, and some of the most recognizable projects within the Minecraft community. Discord is great, and we'd love if we could be part of the open source program <3

**Pull request closed without merging**
