### PR TITLE
Add Resonant Rise

### PR DESCRIPTION
**Pull request by TheCodedOne**

### CODE REVIEW

**Comment by SolarionFX** [comment]
The content in the server does not meet the Open Source standards. Please reevaluate the contents within the server before sending in another request.

**Comment by Lanse505** [comment]
Could you elaborate on what open source standards we are supposte to follow?

**Comment by ChipWolf** [comment]
@SolarionFX we're an open source development community, the code is open source and is approved by Atlassian, Adaptavist, and JetBrains as such. Please elaborate which standards we're not meeting on your end.

**Comment by jfurrow** [comment]
I reviewed your community and didn't see anything related to open source development, but maybe I missed it. Where does this take place?

**Pull request closed without merging**
