### PR TITLE
Add RATELIMITED Discord

### PR DESCRIPTION
**Pull request by gtsatsis**

### CODE REVIEW

**Comment by LordBonzi** [comment]
No

**Comment by Hexexpeck** [comment]
:eyes:

**Comment by Kodehawa** [comment]
now with more proceidures

**Comment by nullpixel** [comment]
Please no, stolen code != OSS

**Comment by gtsatsis** [comment]
@nullpixel If you actually cared to research, you'd fins out that we have our own API now.. RatelimitedME/RLAPI

**Comment by jfurrow** [comment]
Hi @gtsatsis! Sorry for the delay, but at this time we are not accepting Discord-focused projects. I've just updated [the README](https://github.com/discordapp/discord-open-source/blob/master/README.md) accordingly.

Thank you for your interest!

**Comment by Seriell** [comment]
I dunno if I'm missing something here, but RATELIMTED doesn't seem overly discord focused. Sure it's services are used inside discord and were probably inspired by Discord culture, but at the end of the day it's a "POMF Protocol and ShareX Compatible Uploading Service" (From their own github page), and not a Discord bot/api related thing.

Of course I could be wrong here, just thought I'd pitch in.

**Comment by gtsatsis** [comment]
Even with that reasoning out of the way, we don't meet the requirements,
sadly :(

**Comment by Seriell** [comment]
Oh alright then, that's fair enough.

**Comment by jfurrow** [comment]
@Seriell You're absolutely right, I'm not sure why I though it was discord-related. Sorry about that.

Unfortunately this does not meet the community size requirements.

**Pull request closed without merging**
