### PR TITLE
RPCS3: Provide permanent invite link and improve description

### PR DESCRIPTION
**Pull request by MrHulaHoop**
Addresses requirements from #32 and also improve readability of the description.

### CODE REVIEW

**Comment by jfurrow** [comment]
The invite code `jUzhM` appears to be invalid.

**Comment by MrHulaHoop** [comment]
Not sure what went wrong last time...

Hopefully it works now 
invite link

**Comment by jfurrow** [comment]
That looks good, thanks!

**Comment by jfurrow** [comment]
@MrHulaHoop The invite is inactive again... I'm going to have to remove `RPCS3` for now. Please submit another PR when this has been sorted out.

**Comment by AniLeo** [comment]
Server admin here: I have no idea what's happening with those invites
I've generated a permanent one: a6zm2T8
We also have a permalink from discord.me: discord.me/rpcs3

**Comment by jfurrow** [comment]
@AniLeo The permanent invite code (`a6zm2T8`) you provided seems to be working, thanks!

**Pull request merged**
